// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var NiceComponents_test = 0;

var NiceComponents = 0;

exports.NiceComponents_test = NiceComponents_test;
exports.NiceComponents      = NiceComponents;
/* No side effect */
