// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var Nice        = require("bs-nice/lib/js/src/nice.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function make(tag, $staropt$star, styles) {
  var debugName = $staropt$star ? $staropt$star[0] : "";
  var component = ReasonReact.statelessComponent(debugName);
  var className = Nice.css(styles);
  var make$1 = function (props, children) {
    var newrecord = component.slice();
    newrecord[/* render */9] = (function () {
        var cls = {
          className: className
        };
        if (props) {
          return ReasonReact.createDomElement(tag, Object.assign(cls, props[0]), children);
        } else {
          return ReasonReact.createDomElement(tag, cls, children);
        }
      });
    return newrecord;
  };
  return /* module */[
          /* __tag */tag,
          /* __debugName */debugName,
          /* __styles */styles,
          /* className */className,
          /* component */component,
          /* make */make$1
        ];
}

function addStyles(newStyles, x) {
  return make(x[/* __tag */0], /* Some */[x[/* __debugName */1]], $$Array.append(newStyles, x[/* __styles */2]));
}

function AddStyles(NewStyles) {
  return (function (Component) {
      var __styles = $$Array.append(NewStyles[/* newStyles */0], Component[/* __styles */2]);
      var className = Nice.css(__styles);
      return /* module */[
              /* __tag */Component[0],
              /* __debugName */Component[1],
              /* component */Component[4],
              /* make */Component[5],
              /* __styles */__styles,
              /* className */className
            ];
    });
}

function getStyles(html) {
  return List.fold_left((function (a, b) {
                return a + b;
              }), "", Nice.extract(html)[/* css */0]);
}

function a(param, param$1) {
  return make("a", param, param$1);
}

function abbr(param, param$1) {
  return make("abbr", param, param$1);
}

function acronym(param, param$1) {
  return make("acronym", param, param$1);
}

function address(param, param$1) {
  return make("address", param, param$1);
}

function applet(param, param$1) {
  return make("applet", param, param$1);
}

function area(param, param$1) {
  return make("area", param, param$1);
}

function article(param, param$1) {
  return make("article", param, param$1);
}

function aside(param, param$1) {
  return make("aside", param, param$1);
}

function audio(param, param$1) {
  return make("audio", param, param$1);
}

function b(param, param$1) {
  return make("b", param, param$1);
}

function base(param, param$1) {
  return make("base", param, param$1);
}

function basefont(param, param$1) {
  return make("basefont", param, param$1);
}

function bdi(param, param$1) {
  return make("bdi", param, param$1);
}

function bdo(param, param$1) {
  return make("bdo", param, param$1);
}

function bgsound(param, param$1) {
  return make("bgsound", param, param$1);
}

function big(param, param$1) {
  return make("big", param, param$1);
}

function blink(param, param$1) {
  return make("blink", param, param$1);
}

function blockquote(param, param$1) {
  return make("blockquote", param, param$1);
}

function body(param, param$1) {
  return make("body", param, param$1);
}

function br(param, param$1) {
  return make("br", param, param$1);
}

function button(param, param$1) {
  return make("button", param, param$1);
}

function canvas(param, param$1) {
  return make("canvas", param, param$1);
}

function caption(param, param$1) {
  return make("caption", param, param$1);
}

function center(param, param$1) {
  return make("center", param, param$1);
}

function cite(param, param$1) {
  return make("cite", param, param$1);
}

function code(param, param$1) {
  return make("code", param, param$1);
}

function col(param, param$1) {
  return make("col", param, param$1);
}

function colgroup(param, param$1) {
  return make("colgroup", param, param$1);
}

function command(param, param$1) {
  return make("command", param, param$1);
}

function content(param, param$1) {
  return make("content", param, param$1);
}

function data(param, param$1) {
  return make("data", param, param$1);
}

function datalist(param, param$1) {
  return make("datalist", param, param$1);
}

function dd(param, param$1) {
  return make("dd", param, param$1);
}

function del(param, param$1) {
  return make("del", param, param$1);
}

function details(param, param$1) {
  return make("details", param, param$1);
}

function dfn(param, param$1) {
  return make("dfn", param, param$1);
}

function dialog(param, param$1) {
  return make("dialog", param, param$1);
}

function dir(param, param$1) {
  return make("dir", param, param$1);
}

function div(param, param$1) {
  return make("div", param, param$1);
}

function dl(param, param$1) {
  return make("dl", param, param$1);
}

function dt(param, param$1) {
  return make("dt", param, param$1);
}

function element(param, param$1) {
  return make("element", param, param$1);
}

function em(param, param$1) {
  return make("em", param, param$1);
}

function embed(param, param$1) {
  return make("embed", param, param$1);
}

function fieldset(param, param$1) {
  return make("fieldset", param, param$1);
}

function figcaption(param, param$1) {
  return make("figcaption", param, param$1);
}

function figure(param, param$1) {
  return make("figure", param, param$1);
}

function font(param, param$1) {
  return make("font", param, param$1);
}

function footer(param, param$1) {
  return make("footer", param, param$1);
}

function form(param, param$1) {
  return make("form", param, param$1);
}

function frame(param, param$1) {
  return make("frame", param, param$1);
}

function frameset(param, param$1) {
  return make("frameset", param, param$1);
}

function h1(param, param$1) {
  return make("h1", param, param$1);
}

function h2(param, param$1) {
  return make("h2", param, param$1);
}

function h3(param, param$1) {
  return make("h3", param, param$1);
}

function h4(param, param$1) {
  return make("h4", param, param$1);
}

function h5(param, param$1) {
  return make("h5", param, param$1);
}

function h6(param, param$1) {
  return make("h6", param, param$1);
}

function head(param, param$1) {
  return make("head", param, param$1);
}

function header(param, param$1) {
  return make("header", param, param$1);
}

function hgroup(param, param$1) {
  return make("hgroup", param, param$1);
}

function hr(param, param$1) {
  return make("hr", param, param$1);
}

function html(param, param$1) {
  return make("html", param, param$1);
}

function i(param, param$1) {
  return make("i", param, param$1);
}

function iframe(param, param$1) {
  return make("iframe", param, param$1);
}

function img(param, param$1) {
  return make("img", param, param$1);
}

function input(param, param$1) {
  return make("input", param, param$1);
}

function ins(param, param$1) {
  return make("ins", param, param$1);
}

function isindex(param, param$1) {
  return make("isindex", param, param$1);
}

function kbd(param, param$1) {
  return make("kbd", param, param$1);
}

function keygen(param, param$1) {
  return make("keygen", param, param$1);
}

function label(param, param$1) {
  return make("label", param, param$1);
}

function legend(param, param$1) {
  return make("legend", param, param$1);
}

function li(param, param$1) {
  return make("li", param, param$1);
}

function link(param, param$1) {
  return make("link", param, param$1);
}

function listing(param, param$1) {
  return make("listing", param, param$1);
}

function main(param, param$1) {
  return make("main", param, param$1);
}

function map(param, param$1) {
  return make("map", param, param$1);
}

function mark(param, param$1) {
  return make("mark", param, param$1);
}

function marquee(param, param$1) {
  return make("marquee", param, param$1);
}

function math(param, param$1) {
  return make("math", param, param$1);
}

function menu(param, param$1) {
  return make("menu", param, param$1);
}

function menuitem(param, param$1) {
  return make("menuitem", param, param$1);
}

function meta(param, param$1) {
  return make("meta", param, param$1);
}

function meter(param, param$1) {
  return make("meter", param, param$1);
}

function multicol(param, param$1) {
  return make("multicol", param, param$1);
}

function nav(param, param$1) {
  return make("nav", param, param$1);
}

function nextid(param, param$1) {
  return make("nextid", param, param$1);
}

function nobr(param, param$1) {
  return make("nobr", param, param$1);
}

function noembed(param, param$1) {
  return make("noembed", param, param$1);
}

function noframes(param, param$1) {
  return make("noframes", param, param$1);
}

function noscript(param, param$1) {
  return make("noscript", param, param$1);
}

function object_(param, param$1) {
  return make("object", param, param$1);
}

function ol(param, param$1) {
  return make("ol", param, param$1);
}

function optgroup(param, param$1) {
  return make("optgroup", param, param$1);
}

function option(param, param$1) {
  return make("option", param, param$1);
}

function output(param, param$1) {
  return make("output", param, param$1);
}

function p(param, param$1) {
  return make("p", param, param$1);
}

function param(param$1, param$2) {
  return make("param", param$1, param$2);
}

function picture(param, param$1) {
  return make("picture", param, param$1);
}

function plaintext(param, param$1) {
  return make("plaintext", param, param$1);
}

function pre(param, param$1) {
  return make("pre", param, param$1);
}

function progress(param, param$1) {
  return make("progress", param, param$1);
}

function q(param, param$1) {
  return make("q", param, param$1);
}

function rb(param, param$1) {
  return make("rb", param, param$1);
}

function rbc(param, param$1) {
  return make("rbc", param, param$1);
}

function rp(param, param$1) {
  return make("rp", param, param$1);
}

function rt(param, param$1) {
  return make("rt", param, param$1);
}

function rtc(param, param$1) {
  return make("rtc", param, param$1);
}

function ruby(param, param$1) {
  return make("ruby", param, param$1);
}

function s(param, param$1) {
  return make("s", param, param$1);
}

function samp(param, param$1) {
  return make("samp", param, param$1);
}

function script(param, param$1) {
  return make("script", param, param$1);
}

function section(param, param$1) {
  return make("section", param, param$1);
}

function select(param, param$1) {
  return make("select", param, param$1);
}

function shadow(param, param$1) {
  return make("shadow", param, param$1);
}

function slot(param, param$1) {
  return make("slot", param, param$1);
}

function small(param, param$1) {
  return make("small", param, param$1);
}

function source(param, param$1) {
  return make("source", param, param$1);
}

function spacer(param, param$1) {
  return make("spacer", param, param$1);
}

function span(param, param$1) {
  return make("span", param, param$1);
}

function strike(param, param$1) {
  return make("strike", param, param$1);
}

function strong(param, param$1) {
  return make("strong", param, param$1);
}

function style(param, param$1) {
  return make("style", param, param$1);
}

function sub(param, param$1) {
  return make("sub", param, param$1);
}

function svg(param, param$1) {
  return make("svg", param, param$1);
}

function table(param, param$1) {
  return make("table", param, param$1);
}

function tbody(param, param$1) {
  return make("tbody", param, param$1);
}

function td(param, param$1) {
  return make("td", param, param$1);
}

function template(param, param$1) {
  return make("template", param, param$1);
}

function textarea(param, param$1) {
  return make("textarea", param, param$1);
}

function tfoot(param, param$1) {
  return make("tfoot", param, param$1);
}

function th(param, param$1) {
  return make("th", param, param$1);
}

function thead(param, param$1) {
  return make("thead", param, param$1);
}

function time(param, param$1) {
  return make("time", param, param$1);
}

function title(param, param$1) {
  return make("title", param, param$1);
}

function tr(param, param$1) {
  return make("tr", param, param$1);
}

function track(param, param$1) {
  return make("track", param, param$1);
}

function tt(param, param$1) {
  return make("tt", param, param$1);
}

function u(param, param$1) {
  return make("u", param, param$1);
}

function ul(param, param$1) {
  return make("ul", param, param$1);
}

function $$var(param, param$1) {
  return make("var", param, param$1);
}

function video(param, param$1) {
  return make("video", param, param$1);
}

function wbr(param, param$1) {
  return make("wbr", param, param$1);
}

function xmp(param, param$1) {
  return make("xmp", param, param$1);
}

exports.make       = make;
exports.addStyles  = addStyles;
exports.AddStyles  = AddStyles;
exports.getStyles  = getStyles;
exports.a          = a;
exports.abbr       = abbr;
exports.acronym    = acronym;
exports.address    = address;
exports.applet     = applet;
exports.area       = area;
exports.article    = article;
exports.aside      = aside;
exports.audio      = audio;
exports.b          = b;
exports.base       = base;
exports.basefont   = basefont;
exports.bdi        = bdi;
exports.bdo        = bdo;
exports.bgsound    = bgsound;
exports.big        = big;
exports.blink      = blink;
exports.blockquote = blockquote;
exports.body       = body;
exports.br         = br;
exports.button     = button;
exports.canvas     = canvas;
exports.caption    = caption;
exports.center     = center;
exports.cite       = cite;
exports.code       = code;
exports.col        = col;
exports.colgroup   = colgroup;
exports.command    = command;
exports.content    = content;
exports.data       = data;
exports.datalist   = datalist;
exports.dd         = dd;
exports.del        = del;
exports.details    = details;
exports.dfn        = dfn;
exports.dialog     = dialog;
exports.dir        = dir;
exports.div        = div;
exports.dl         = dl;
exports.dt         = dt;
exports.element    = element;
exports.em         = em;
exports.embed      = embed;
exports.fieldset   = fieldset;
exports.figcaption = figcaption;
exports.figure     = figure;
exports.font       = font;
exports.footer     = footer;
exports.form       = form;
exports.frame      = frame;
exports.frameset   = frameset;
exports.h1         = h1;
exports.h2         = h2;
exports.h3         = h3;
exports.h4         = h4;
exports.h5         = h5;
exports.h6         = h6;
exports.head       = head;
exports.header     = header;
exports.hgroup     = hgroup;
exports.hr         = hr;
exports.html       = html;
exports.i          = i;
exports.iframe     = iframe;
exports.img        = img;
exports.input      = input;
exports.ins        = ins;
exports.isindex    = isindex;
exports.kbd        = kbd;
exports.keygen     = keygen;
exports.label      = label;
exports.legend     = legend;
exports.li         = li;
exports.link       = link;
exports.listing    = listing;
exports.main       = main;
exports.map        = map;
exports.mark       = mark;
exports.marquee    = marquee;
exports.math       = math;
exports.menu       = menu;
exports.menuitem   = menuitem;
exports.meta       = meta;
exports.meter      = meter;
exports.multicol   = multicol;
exports.nav        = nav;
exports.nextid     = nextid;
exports.nobr       = nobr;
exports.noembed    = noembed;
exports.noframes   = noframes;
exports.noscript   = noscript;
exports.object_    = object_;
exports.ol         = ol;
exports.optgroup   = optgroup;
exports.option     = option;
exports.output     = output;
exports.p          = p;
exports.param      = param;
exports.picture    = picture;
exports.plaintext  = plaintext;
exports.pre        = pre;
exports.progress   = progress;
exports.q          = q;
exports.rb         = rb;
exports.rbc        = rbc;
exports.rp         = rp;
exports.rt         = rt;
exports.rtc        = rtc;
exports.ruby       = ruby;
exports.s          = s;
exports.samp       = samp;
exports.script     = script;
exports.section    = section;
exports.select     = select;
exports.shadow     = shadow;
exports.slot       = slot;
exports.small      = small;
exports.source     = source;
exports.spacer     = spacer;
exports.span       = span;
exports.strike     = strike;
exports.strong     = strong;
exports.style      = style;
exports.sub        = sub;
exports.svg        = svg;
exports.table      = table;
exports.tbody      = tbody;
exports.td         = td;
exports.template   = template;
exports.textarea   = textarea;
exports.tfoot      = tfoot;
exports.th         = th;
exports.thead      = thead;
exports.time       = time;
exports.title      = title;
exports.tr         = tr;
exports.track      = track;
exports.tt         = tt;
exports.u          = u;
exports.ul         = ul;
exports.$$var      = $$var;
exports.video      = video;
exports.wbr        = wbr;
exports.xmp        = xmp;
/* Nice Not a pure module */
